/**
 * Router-specific Cloudflare Worker entry point for vinext App Router.
 *
 * New projects should usually use the router-selected entry in wrangler.jsonc:
 *   "main": "vinext/server/fetch-handler"
 *
 * This App Router entry remains available for existing configs and for custom
 * workers that need to opt into the App Router handler explicitly:
 *   "main": "vinext/server/app-router-entry"
 *
 * Or import and delegate to it from a custom worker:
 *   import handler from "vinext/server/app-router-entry";
 *   return handler.fetch(request, env, ctx);
 *
 * This file runs in the RSC environment. Configure the Cloudflare plugin with:
 *   cloudflare({ viteEnvironment: { name: "rsc", childEnvironments: ["ssr"] } })
 */

import "./server-globals.js";
// Virtual module generated by vinext at build time. The default export is
// the request handler; `__assetPrefix` and `__basePath` are named exports
// inlined from next.config (both as string literals) so this worker can
// recognise asset-shaped requests without invoking the handler. Types
// live in `virtual-vinext-rsc-entry.d.ts`; the generator is in
// `entries/app-rsc-entry.ts`.
import rscHandler, {
  __assetPrefix as __rscAssetPrefix,
  __basePath as __rscBasePath,
  __imageAllowedWidths as __rscImageAllowedWidths,
  __imageConfig as __rscImageConfig,
} from "virtual:vinext-rsc-entry";
import { runWithExecutionContext, type ExecutionContextLike } from "vinext/shims/request-context";
// @ts-expect-error -- virtual module resolved by vinext at build time
import { registerConfiguredCacheAdapters } from "virtual:vinext-cache-adapters";
// @ts-expect-error -- virtual module resolved by vinext at build time
import { registerConfiguredImageOptimizer } from "virtual:vinext-image-adapters";
import {
  getImageOptimizer,
  handleConfiguredImageOptimization,
  isImageOptimizationPath,
} from "./image-optimization.js";
import { finalizeMissingStaticAssetResponse, resolveStaticAssetSignal } from "./worker-utils.js";
import {
  cloneRequestWithHeaders,
  filterInternalHeaders,
  isOpenRedirectShaped,
} from "./request-pipeline.js";
import { VINEXT_PRERENDER_ROUTE_PARAMS_HEADER, VINEXT_REVALIDATE_HOST_HEADER } from "./headers.js";
import {
  readTrustedPrerenderRouteParams,
  serializePrerenderRouteParamsHeader,
} from "./prerender-route-params.js";
import {
  badRequestResponse,
  notFoundResponse,
  notFoundStaticAssetResponse,
} from "./http-error-responses.js";
import { assetPrefixPathname, isNextStaticPath } from "../utils/asset-prefix.js";
import { createWorkerRevalidationContext } from "./worker-revalidation-context.js";

// Precompute the path components used for `_next/static/*` 404 short-circuit
// detection. Both `__basePath` and `__assetPrefix` are inlined as
// compile-time constants in the generated RSC entry — see entries/app-rsc-entry.ts.
const __workerBasePath: string = typeof __rscBasePath === "string" ? __rscBasePath : "";
const __workerAssetPathPrefix: string = assetPrefixPathname(
  typeof __rscAssetPrefix === "string" ? __rscAssetPrefix : "",
);

type WorkerAssetEnv = {
  ASSETS?: {
    fetch(request: Request): Promise<Response> | Response;
  };
};

export default {
  async fetch(
    request: Request,
    env?: WorkerAssetEnv,
    ctx?: ExecutionContextLike,
  ): Promise<Response> {
    return handleRequest(request, env, ctx);
  },
};

async function handleRequest(
  request: Request,
  env: WorkerAssetEnv | undefined,
  platformCtx: ExecutionContextLike | undefined,
): Promise<Response> {
  // The Node production server calls this Worker-style entry with a
  // server-owned loopback origin and must retain its HTTP revalidation path.
  // Cloudflare requests instead receive an in-process dispatcher so the
  // credential never leaves the Worker isolate.
  const ctx = platformCtx?.trustedRevalidateOrigin
    ? platformCtx
    : createWorkerRevalidationContext(platformCtx, (internalRequest, internalCtx) =>
        handleRequest(internalRequest, env, internalCtx),
      );

  // Register config-driven cache adapters before any rendering touches the cache.
  registerConfiguredCacheAdapters(env as Record<string, unknown> | undefined);
  registerConfiguredImageOptimizer(env as Record<string, unknown> | undefined);

  const url = new URL(request.url);

  if (isImageOptimizationPath(url.pathname) && env?.ASSETS && getImageOptimizer()) {
    const assetFetcher = env.ASSETS;
    return handleConfiguredImageOptimization(
      request,
      (assetPath) =>
        Promise.resolve(assetFetcher.fetch(new Request(new URL(assetPath, request.url)))),
      __rscImageAllowedWidths,
      __rscImageConfig,
    );
  }

  // Block protocol-relative URL open redirects (//evil.com/, /\evil.com/,
  // /%5Cevil.com/, /%2F/evil.com/). Check BEFORE decode so both literal and
  // percent-encoded variants are caught — encoded forms survive segment-wise
  // decoding and would otherwise reach trailing-slash redirect emitters.
  if (isOpenRedirectShaped(url.pathname)) {
    return notFoundResponse();
  }

  // Validate that percent-encoding is well-formed. The RSC handler performs
  // the actual decode + normalize; we only check here to return a clean 400
  // instead of letting a malformed sequence crash downstream.
  try {
    decodeURIComponent(url.pathname);
  } catch {
    // Malformed percent-encoding (e.g. /%E0%A4%A) — return 400 instead of throwing.
    return badRequestResponse();
  }

  // Valid assets are served by Cloudflare's ASSETS binding before the worker
  // is invoked. Missing asset-shaped requests still need to reach middleware
  // so it can rewrite or respond; a final 404 is converted back to Next.js's
  // canonical plain-text static-file response below.
  const missingBuildAsset = isNextStaticPath(
    url.pathname,
    __workerBasePath,
    __workerAssetPathPrefix,
  );

  // Strip internal headers from inbound requests before any handler or
  // middleware sees them. Must happen before the RSC handler runs.
  // Builds a new Headers — Request.headers is immutable in Workers.
  {
    const prerenderRouteParamsPayload = readTrustedPrerenderRouteParams(request);
    const filteredHeaders = ctx.isInternalPagesRevalidation
      ? new Headers(request.headers)
      : filterInternalHeaders(request.headers);
    filteredHeaders.delete(VINEXT_REVALIDATE_HOST_HEADER);
    const prerenderRouteParamsHeader = serializePrerenderRouteParamsHeader(
      prerenderRouteParamsPayload,
    );
    if (prerenderRouteParamsHeader !== null) {
      filteredHeaders.set(VINEXT_PRERENDER_ROUTE_PARAMS_HEADER, prerenderRouteParamsHeader);
    }
    request = cloneRequestWithHeaders(request, filteredHeaders);
  }

  // Do NOT decode/normalize the pathname here. The RSC handler
  // (virtual:vinext-rsc-entry) is the single point of decoding — it calls
  // decodeURIComponent + normalizePath on the incoming URL. Decoding here
  // AND in the handler would double-decode, causing inconsistent path
  // matching between middleware and routing.

  // Delegate to RSC handler (which decodes + normalizes the pathname itself),
  // wrapping in the ExecutionContext ALS scope so downstream code can reach
  // ctx.waitUntil() without having ctx threaded through every call site.
  const handleFn = () => rscHandler(request, ctx);
  const result = await (ctx ? runWithExecutionContext(ctx, handleFn) : handleFn());

  if (result instanceof Response) {
    let response = result;
    if (env?.ASSETS) {
      const assetFetcher = env.ASSETS;
      const assetResponse = await resolveStaticAssetSignal(response, {
        fetchAsset: (path) =>
          Promise.resolve(assetFetcher.fetch(new Request(new URL(path, request.url)))),
      });
      if (assetResponse) response = assetResponse;
    }
    return finalizeMissingStaticAssetResponse(response, missingBuildAsset);
  }

  if (result === null || result === undefined) {
    return missingBuildAsset ? notFoundStaticAssetResponse() : notFoundResponse();
  }

  return new Response(String(result), { status: 200 });
}
